name:                free-generators
version:             0.1.0.0
github:              "hgoldstein95/free-generators"
license:             MIT
author:              "Harrison Goldstein"
maintainer:          "harrisongoldste.in"
copyright:           "2022 Harrison Goldstein"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/tyche#readme>

dependencies:
- base >= 4.7
- QuickCheck
- containers
- mtl
- unordered-containers
- hashable
- text-metrics
- text
- template-haskell
- lens
- unbound-generics

library:
  source-dirs: src

executables:
  tyche-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - free-generators

tests:
  tyche-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - free-generators
